spring.application.name=sistema
spring.datasource.url=jdbc:postgresql://dpg-d496iqk9c44c73bgv16g-a.oregon-postgres.render.com:5432/rd_sistemaspring.datasource.username=luis
spring.datasource.password=sYdFXEXC4w6W1GdFjQYVwaT3rP0jOBnd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}
spring.profiles.active=prod

jwt.expiration=3600000
jwt.secret=miClaveSecretaMuySegura123